### ISSUE TITLE
User Login (with Google account)

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/x-map#12]
## User Story

As a user, I want to login with my credentials so that I can use the app.
### Scenario 1: Existing user, login with google account
- Given I already have registered my account,
- And I'm NOT logged in,
- Then I'm able to see the login panel,
- When I click in "Login with Google account",
- Then I see a pop up page asking for confirmation,
- When I select my account,
- Then I'm redirected to the app,
- Then I can confirm that I'm logged in.
## Notes
- Design to be provided #7

**Comment by jedrzej** [comment]
It should be possible to switch between authentication methods so that login form can be used locally, while google login would be used on Prod

**Comment by bernardodiasc** [comment]
Do we'll keep both auth methods? Looks like the Google auth is good enough for any case by now, and first-time users (#13) also working smooth.

**Comment by jedrzej** [comment]
Google Login works locally, so no need to keep the old login form. I thought of keeping both when I was not sure we can use google auth on localhost

**Comment by bernardodiasc** [comment]
Perfect :+1:
