### ISSUE TITLE
Add unit tests for reducers

### ISSUE THREAD

**Issue by jedrzej** [x-team/x-map#125]
We have some tests, but not for all reducers. They don't cover all actions. Initial states used in testing and in reducers should be unified as well.

**Comment by diegodurli** [comment]
Hi @jedrzej!

Could I start working on this one? Wondering about plans on v1.1 milestone!

**Comment by jedrzej** [comment]
Sure @diegodurli, feel free to pick that up. I'd love to get started with v1.1 as well, @jkbdbrnwsk is there anything we're waiting  for? I'm not 100% sure if the milestones we discussed some time ago are still valid.

**Comment by devranowski** [comment]
@jedrzej, will ping you on Slack.
