### ISSUE TITLE
User Registration (with Google account)

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/x-map#13]
## User Story

As a guest user, I want to register new account with my credentials so that I can use the app.
### Scenario 1: Guest user, register with google account
- Given it's my first time visiting the site,
- And I'm not logged in,
- Then I'm able to see the login panel,
- When I click in "Login with Google account",
- Then I see a pop up page asking for confirmation,
- When I select my account,
- Then I'm redirected to the app home screen.
## Notes
- Design to be provided #7

**Comment by jedrzej** [comment]
It should be possible to switch between authentication methods so that login form can be used locally, while google login would be used on Prod
