### ISSUE TITLE
Show a single conference

### ISSUE THREAD

**Issue by jedrzej** [x-team/x-map#138]
When I click on a conference, I can see its details:
- name
- location (city/country)
- website
- dates
- list of x-teamers going
- pictures (optional, default to a placeholder)

Additional interactions:
- clicking on a conference from a conference list the map will center on the conference with it's default zoom
- clicking on the address in the conference  card it will open new tab with google maps centered on the location
- clicking on one of the x-teamer from the paritcipant list will open detailed card for the choosen x-teamer
- clicking "back" btn will display conference search 

Definition of done:
- conference card is a component easily be extractable into a separete repository
- card is scrollable on small screens
- preloader in case of async requests for any of the lists
- conference details has it's own routing so it can be copy pasted between x-teamers and it will lead to the same screen
- tests

<img width="360" alt="screen_shot_2016-06-02_at_8 15 30_am_720" src="https://cloud.githubusercontent.com/assets/2013380/15741520/56861aac-28ba-11e6-817f-96ee1e6ccc7a.png">

**Comment by bernardodiasc** [comment]
Hey, this is very good! Have 2 questions about additional interactions:

> clicking on the address in the conference card it will open new tab with google maps centered on the location

I think the tabs need to be included, it's not something existing now maybe require extra effort.

> clicking "back" btn will display conference search

This seems to be related to https://github.com/x-team/x-map/issues/21, the mockups are really good @peterKaleta, I'll include there. :)
