### ISSUE TITLE
Make avatars round in profile page

### ISSUE THREAD

**Issue by jedrzej** [x-team/x-map#152]
Avatars in profile list are round, yet in profile page view they're displayed as they are in Google, so square avatars are still square

**Comment by bernardodiasc** [comment]
A suggestion is to use the space for poster photo(s) instead avatar in the profile page.

**Comment by jedrzej** [comment]
Posters are great, but in order to have them we'd need to implement file upload, which will be much more complicated. I just thought that for the time being we could just apply the same style there as we have in profile list so that square avatars look nice as well.
