### ISSUE TITLE
Google Maps API warning

### ISSUE THREAD

**Issue by devranowski** [x-team/x-map#163]
Rubens reported this issue: https://www.dropbox.com/s/6tfotfvupcnjz97/Screenshot%202016-03-29%2013.47.16.png?dl=0

**Comment by diegodurli** [comment]
Hi @jkbdbrnwsk,

Would this be something I could jump in and start taking a look at?
It may not be highest priority though, that's why I wanted to reach out before.

Cheers

**Comment by devranowski** [comment]
Hey @diegodurli!

Absolutely! All yours. :)

Much appreciated!

**Comment by diegodurli** [comment]
Thank you @jkbdbrnwsk!

Will pick up it tomorrow and start working on it!

Cheers

**Comment by devranowski** [comment]
Awesome!

**Comment by diegodurli** [comment]
Hey @jkbdbrnwsk!

Got into this warning. Basically, it's just a matter of setting an API Key, specifically on "google-maps" npm package, as shown [here](https://www.npmjs.com/package/google-maps#own-api-key).

Do we have a "central" google account to create this API Key?
If we have a "X-Map Project" on Google Developer Console, that's the place to go.

I've created an API Key in my account and tested locally, warning is gone.

**Comment by jedrzej** [comment]
@jkbdbrnwsk @diegodurli: I've used my own account to register the app in google. I agree it would be great to have x-team's app registered using some kind of x-team's google account.

**Comment by diegodurli** [comment]
Exactly @jedrzej, that would be ideal!

@jedrzej, since you have it now under your account, would you be ok adding this api key?  Just to move forward on this one, since creating this central account can take some time.

**Comment by devranowski** [comment]
Credentials sent on Slack. :)

**Comment by jedrzej** [comment]
Fixed in https://github.com/x-team/x-map/pull/171

**Comment by diegodurli** [comment]
Will close this one since it was fixed in #171.
