### ISSUE TITLE
Installation Issue with Docker - Missing Info

### ISSUE THREAD

**Issue by diegodurli** [x-team/x-map#167]
Hi guys,

I've been through a problem while installing the environment locally.
It happened specifically when running:

```
docker-compose run web composer build
```

As we can see here:

![Issue Image](http://s32.postimg.org/cl05pzvbp/Screen_Shot_2016_05_02_at_5_06_39_PM.png)

I did some research and found that this issue is still open, as we can see [here](https://github.com/docker/compose/issues/2180#issuecomment-207789989).

In brief, there are two possible solutions for now:
1. `eval $(docker-machine env default)`
2. Assign to `.bash_profile` the output from `eval $(docker-machine env default)` 

I applied the first option and it worked fine.

Do you guys want me to submit a PR updating the Installation Docs with this info?

Cheers

**Comment by jedrzej** [comment]
Sure, go for it! :)

**Comment by diegodurli** [comment]
Done @jedrzej, just let me know if is fine for you!

**Comment by bernardodiasc** [comment]
Nice, same thing here, I use the described solution 1). 👍
