### ISSUE TITLE
Display marker on the map for the currently viewed conference

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/x-map#20]
## User story

As a user, I want to see a map marker to learn the exact position of conference I'm currently viewing.
## Acceptance Criteria
- map marker is a pin with a  conference logo inside
- map marker defaults to X logo on the white background in case of no conference logo available
- map marker is a react component (might involve implementing react google maps - to be checked)
- zoom should be configurable
### Scenario 1: Display marker on the map

Given I'm logged in,
When I'm accessing details of a given conference
Then the map will move and zoom to location of conference and the pin
### Design concept

(just a sketch, do it your own way ;) )

<img width="102" alt="screen shot 2016-06-08 at 09 30 14" src="https://cloud.githubusercontent.com/assets/2013380/15886154/b1c289be-2d5b-11e6-9a55-c240ef2cd0b5.png">

**Comment by bernardodiasc** [comment]
I see that the purpose of this issue was changed from "view all conferences" to "view only the current selected". We no longer plan to have all conferences pinned in the map? Why?

I think this was the case of new feature instead a replacement. We can have both functionalities without problem.

**Comment by diegodurli** [comment]
Currently, once you click `Conferences` button, it show all conferences on map.
Then, once you select a specific one, we zoom in and show only that one.

It has both behaviors now.
