### ISSUE TITLE
Display a list of all conferences in a panel

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/x-map#21]
## User story

As a user, I want to see all events that will happen in the world so that I can program mysellf to attend the event. List will be sorted by starting date, it will contain: conference name, dates, city/country, number of x-teamers going.

<img width="649" alt="screen shot 2016-06-02 at 8 15 36 am" src="https://cloud.githubusercontent.com/assets/131859/15758218/f2c28246-28df-11e6-8eef-f5051b9a01f3.png">
### Scenario 1: Display schedule of conferences

Given I'm logged in,
When I click in the "Conferences" button located in the header,
Then I see all conferences listed in a panel,
And I see the conferences sorted alphabetically from top to bottom,
And I see the first conference starting in a date in the present of future,
And I see that conferences are grouped by months,
And I see copy of conference name, country, city, date, numbers of x-teamers planning to attend.
## Notes
- More scenarios to be described:
  - Using filter input;
  - Filter narrowing options;
  - Clicking in a conference;
  - Hovering a conference (?);
  - Hovering attendees icon (?);

**Comment by jedrzej** [comment]
I assume that by "event" you mean a conference or similar?

**Comment by bernardodiasc** [comment]
yes!
this will be moved to v1.1?

**Comment by bernardodiasc** [comment]
@jedrzej @peterKaleta, updated description of this issue. Please review if is accordingly with expectations, still need to write few scenarios for detailed interactions, but the single scenario described can be enough as DoD of this issue (plus tests). Otherwise will be too much thing into a single PR/Commit/Review. Thanks!
