### ISSUE TITLE
Update readme with instructions on how to run the application locally

### ISSUE THREAD

**Issue by jedrzej** [x-team/x-map#3]

**Comment by bernardodiasc** [comment]
In order for us to go open source, we need to make a bunch of definitions before launch v1.0.
- Contribution workflow
- Developement workflow
  - Technical approach
  - Server details
  - Client details
- ... (suggestions?)

One goal is to write short list of links in `CONTRIBUTING.md` (as seen here https://github.com/blog/1184-contributing-guidelines), most of the detailed notes can be stored in the Wiki https://github.com/x-team/x-map/wiki, as a suggestion.

Also interesting reading https://guides.github.com/activities/contributing-to-open-source/

---

One suggestions of the usage in the `README.md` is to have brief descriptions of what is this project and other general information, like the stack used, something like:
- Roadmap v1.0
  - Version goals
  - What is X-Map
  - Schedule
  - How others can contribute?
- ...
