### ISSUE TITLE
Create issues based on MVP scope

### ISSUE THREAD

**Issue by jedrzej** [x-team/x-map#4]
# Scope of version 1.0
## End user acceptance criterias
- Authentication
  - Register with email and password #5
  - Register with google account #13
  - Login with email and password #6
  - Login with google account #12
  - Logout #11
  - Admin role #43
- Profiles
  - Display all profiles markers in the map #14
  - Display a list of all profiles in a panel #15
  - View profile information #16
  - Edit profile information #24 
- Teams
  - Display a list off all teams in a panel #34 
  - Add new team #37
  - Delete team #45
  - Join and leave team #40
  - View team profile  #36
  - Edit team #35
- Presentation
  - Design for main layout and common components #7 
## Development tasks
- Server side stuff
- Client side stuff
  - Setup stack workbench
  - Base css for typography, icons, buttons and forms #7
## Organization tasks
- Roadmap (this?)
- Documentation #3
  - Installation 
  - Contribution
  - Development
    - Workflow #25
      - https://en.wikipedia.org/wiki/Acceptance_test-driven_development
      - http://nvie.com/posts/a-successful-git-branching-model/
      - http://semver.org/
      - https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/
    - Frontend #31
      - https://github.com/mxstbr/react-boilerplate
      - http://eslint.org/
      - https://github.com/airbnb/javascript
    - Backend #32
    - REST API
      - http://ec2-52-33-252-13.us-west-2.compute.amazonaws.com/api/doc

**Comment by bernardodiasc** [comment]
Pasting here a short description of the [REST API](http://ec2-52-33-252-13.us-west-2.compute.amazonaws.com/api/doc) as reference:

> - Users - to store user data
> - Content - to store some text data to display in different places of the website
> - Teams - they allow to group users, provide some information about what they work on, we could use them to filter users on the map to show only users from single team
> - Skills - this is example of static user data - it’s not related to a date or geolocation
> - Events - this is what I called for data that is related to time and geolocation, there are a few attributes defined in the schema, but there is also a generic data field that allows arbitrary data - here we can put whatever geojson stuff we need. It also has simple lat/lng fields in case we just want a simple coordinate

**Comment by bernardodiasc** [comment]
The following is moved to https://github.com/x-team/x-map/milestones/X-Map%20v1.1
- Conferences
  - Create a marker by clicking in the map #23 
  - Display all event markers in the map #20 
  - Display a list of all events in a panel #21 

and 
- Profiles
  - Set current location
    - Create a marker by clicking in the map #17 
    - Create a marker in the map from browser geolocation #18 
    - Upload geotagged picture with current location #19

Note: need revision in the ACs too before start.
