### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by jedrzej** [x-team/x-map#5]
## User Story

As a guest user, I want to register new account with my credentials so that I can use the app.
### Scenario 1: New user, register with email and password
- Given I visit the website
- And I'm NOT logged in,
- Then I'm able to see the registration form,
- When I type my email with my new password,
- And user with given email does not exist yet
- Then my account is created and I'm redirected to the app home screen.
### Scenario 2: Existing user, register with email and password
- Given I visit the website
- And I'm NOT logged in,
- Then I'm able to see the registration form,
- When I type my email with my new password,
- And user with given email exists already
- Then I see an error message
## Notes
- Design to be provided #7

**Comment by bernardodiasc** [comment]
I have proposed a unique approach for registration and login steps in #6, please review.

**Comment by bernardodiasc** [comment]
AC updated, I let the Scenario 2 with Google acc authentication, but let's focus in deliver only the scenario 1 for now.

**Comment by bernardodiasc** [comment]
Issue splited, Google account feature will be addressed in #13.
