### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by jedrzej** [x-team/x-map#6]
## User Story

As a user, I want to login with my credentials so that I can use the app.
### Scenario 1: Existing user, login with email and password
- Given I already have registered my account,
- And I'm NOT logged in,
- Then I'm able to see the login panel,
- When I type my email with my new password,
- Then I'm redirected to the app home screen
- And I can confirm that I'm logged in with the provided credentials.
### Scenario 2: Guest user, attempt to login with wrong email or password
- Given I already have registered my account,
- And I'm NOT logged in,
- Then I'm able to see the login panel,
- When I type invalid combination of email and password,
- Then I see an error message and I see the login panel again
## Notes
- Design to be provided #7

**Comment by jedrzej** [comment]
@bernardodiasc Could we split it? I'd start with just a registration/login form as it's the simplest way and relieves us of doing integration with 3rd party app at this point. We could integrate with google at a later stage once we want to grant real users access to the application - it won't block the development.

**Comment by bernardodiasc** [comment]
AC updated, I let the Scenario 2 with Google acc authentication, but let's focus in deliver only the scenario 1 for now.

**Comment by bernardodiasc** [comment]
Issue splited, Google account feature will be addressed in #12.
