### ISSUE TITLE
User interface and experience improvements for Teams page

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/x-map#63]
## User story

As an user,  I want to see a list of all teams so that I can easily see how everyone is organized.
### Scenario 1: List all teams in Teams page

Given I'm logged in,
When I click in "Teams" in the main menu,
Then I see a list of all teams,
And I see each team with name and description,
When I move my cursor over the team information,
Then I see all markers of developers in that team with different style in the map.

**Comment by jedrzej** [comment]
All the fields that are currently supported by the API are already displayed in team page - we can start with those.

**Comment by bernardodiasc** [comment]
This issue is about the Teams page (not the Team profile page), we dont need all inormation we have about teams in the listing page. If I remember correctly you said about Title and a simple description and move the full descripion in the team page, is that correct?

**Comment by bernardodiasc** [comment]
oh, got it https://github.com/x-team/x-map/pull/87 :+1:
