### ISSUE TITLE
Profile Set Location enhancement

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/x-map#66]
## User story

As an user, I want to be able to set or edit my location so then other developers can see where I'm now.
### Scenario 1: Set Location in Profile page

Given I'm logged in,
And I'm in the Profile page,
When I click in "Set Location",
Then I see other page with the copy "Select location on the map",
And my cursor become a pointer,
And I see the lat and long being displayed in the panel copy while a move the cursor,
When I click in the map,
Then I see a marker in the new coordinate,
When I click "Save",
Then I return to the Profile page,
And I can confirm my changes by seeing the marker in the new position.

**Comment by jedrzej** [comment]
Closing as a duplicate. we already have this feature

**Comment by bernardodiasc** [comment]
If you look carefully, the AC doesn't match. It's an enhancement task, improving little details in the experience.

**Comment by jedrzej** [comment]
You mean the panel that shows coordinates? What's the value in having that?

**Comment by bernardodiasc** [comment]
The value is that will show the coordinates while you try to find the spot. There is changes in the cursor look too, that indicates the program is waiting for user action, for instance. Details that improve the experience, see more https://www.youtube.com/watch?v=Fy0aCDmgnxg

**Comment by jedrzej** [comment]
Then feel free to extract that missing feature to a separate ticket. But still I don't see why user would like to see the coordinates they're pointing at with their cursor.
