### ISSUE TITLE
Create base presentation

### ISSUE THREAD

**Issue by jedrzej** [x-team/x-map#7]
# User Story

As an user, I want to see the app with a nice presentation so that I can enjoy the experience.
### Scenario 1: Home screen, returning user
- Given that I'm logged in,
- When I open the app in the home page,
- Then I verify that the elements is in the page is well styled:
  - The header containing:
    - The app logo at the left side;
    - The main menu in the right side;
    - My username and profile picture located in the right side;
  - A map covering all the body of the app;
### Scenario 2: Internal screens
- Given that I'm logged in,
- When I click in one othe the items in the main menu,
- Then I verify that the page do not reload,
- Then I see a panel visible above the map with specific content for the menu item choosed,
- Then I see that any content inside the panel is well styled.
## Notes
- This is pretty much the design task. Since the design will be simple, it will be made coded.
- This task includes base css for typography, icons, buttons and forms.

**Comment by bernardodiasc** [comment]
![1453681379195screensave](https://cloud.githubusercontent.com/assets/131859/12544678/6b5786de-c323-11e5-9260-5902067b3db9.png)
![1453687396286screensave](https://cloud.githubusercontent.com/assets/131859/12544679/6b5f12dc-c323-11e5-9097-41679aee88f8.png)
![1453692678693screensave](https://cloud.githubusercontent.com/assets/131859/12544680/6b83d11c-c323-11e5-90d1-f045a7fb4c57.png)
![1453693142132screensave](https://cloud.githubusercontent.com/assets/131859/12544681/6b89ecd2-c323-11e5-8f39-c952d6a66c03.png)
![1453706212751screensave](https://cloud.githubusercontent.com/assets/131859/12544682/6bb3c516-c323-11e5-876c-b4497cc6dbf2.png)
