### ISSUE TITLE
Unit tests for login/logout reducers

### ISSUE THREAD

**Issue by jedrzej** [x-team/x-map#8]

**Comment by bernardodiasc** [comment]
Let's move this task as part of the deliverables in #6 and #11 ?

I think with our workflow we'll need to send tests together with PR's for each function implemented, right? If the AC works, we should be able to translate that into automated test scripts.

**Comment by jedrzej** [comment]
True, they should be delivered together - feature + test

**Comment by bernardodiasc** [comment]
Nice, so I'll close this issue in favor of the others.
