### ISSUE TITLE
Extract plain components

### ISSUE THREAD

**Issue by jedrzej** [x-team/x-map#85]
Many of our components are using redux's connect functionality to bind state with props, which makes it hard to reuse them. We could split them into 2 components: a plain one and a connected one

**Comment by bernardodiasc** [comment]
Interesting. I see we can

**Comment by bernardodiasc** [comment]
ops, sorry.... clicked in wrong button. I like this idea.

**Comment by bernardodiasc** [comment]
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0 I think this is related to the goal of this issue.

**Comment by jedrzej** [comment]
yeah, that's what I did. We have smart components that represent different pages and care about where data comes froms. The rest just takes all data from its props.
